// Generated by Dagger (https://dagger.dev).
package com.tminus1010.budgetvalue._shared.date_period_getter;

import com.tminus1010.budgetvalue._shared.date_period_getter.data.ISettingsRepo;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DatePeriodGetter_Factory implements Factory<DatePeriodGetter> {
  private final Provider<ISettingsRepo> settingsRepoProvider;

  public DatePeriodGetter_Factory(Provider<ISettingsRepo> settingsRepoProvider) {
    this.settingsRepoProvider = settingsRepoProvider;
  }

  @Override
  public DatePeriodGetter get() {
    return newInstance(settingsRepoProvider.get());
  }

  public static DatePeriodGetter_Factory create(Provider<ISettingsRepo> settingsRepoProvider) {
    return new DatePeriodGetter_Factory(settingsRepoProvider);
  }

  public static DatePeriodGetter newInstance(ISettingsRepo settingsRepo) {
    return new DatePeriodGetter(settingsRepo);
  }
}
